FROM vllm/vllm-openai:latest

# Default value for GPU count
ARG GPU_COUNT=1
ENV TP_SIZE=$GPU_COUNT

# Create an entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN mkdir -p /models/__MODEL_SUBFOLDER__
ADD ./models/__MODEL_SUBFOLDER__ /models/__MODEL_SUBFOLDER__

ENTRYPOINT ["/entrypoint.sh"]