services:
  vllm:
    build: ../vLLM
    ports:
      - "8007:8000"
    environment:
      - MAX_NUM_BATCHED_TOKENS=4096
      - MAX_NUM_SEQS=256
      - MAX_PADDING_LENGTH=256
      - MAX_MODEL_LEN=4096
      - QUANTIZATION=awq
      - TRUST_REMOTE_CODE=true
      - HF_DATASETS_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
      - GPU_MEMORY_UTILIZATION=0.80
    volumes:
      - ../../models:/models
      - ../../data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    command: >
      --model /models/DeepHermes-3-Llama-3-8B-Preview
      --tokenizer /models/DeepHermes-3-Llama-3-8B-Preview
      --dtype=half
      --gpu-memory-utilization=0.80
      --max-model-len=65536

  vllm_embeddings:
    build: ../vLLM
    ports:
      - "8012:8000"
    environment:
      - MAX_NUM_BATCHED_TOKENS=4096
      - MAX_NUM_SEQS=256
      - MAX_PADDING_LENGTH=256
      - MAX_MODEL_LEN=4096
      - QUANTIZATION=awq
      - TRUST_REMOTE_CODE=true
      - HF_DATASETS_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
      - GPU_MEMORY_UTILIZATION=0.10
    volumes:
      - ../../models:/models
      - ../../data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    command: >
      --model /models/bge-base-en-v1.5
      --tokenizer /models/bge-base-en-v1.5
      --dtype=half
      --gpu-memory-utilization=0.10