version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "8007:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0,1
      - MAX_NUM_BATCHED_TOKENS=4096
      - MAX_NUM_SEQS=256
      - MAX_PADDING_LENGTH=256
      - MAX_MODEL_LEN=4096
      - QUANTIZATION=awq
      - TRUST_REMOTE_CODE=true
      - HF_DATASETS_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    volumes:
      - ../../models:/models
      - ../../data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    ipc: host
    command: --model /models/Llama-3.2-1B-Instruct-abliterated --tokenizer /models/Llama-3.2-1B-Instruct-abliterated --dtype=half